name: Notification Service


on:
  push:
    paths:
      -  notification_service/**
    branches:
      -   '**'


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./notification_service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -ntp verify

      -
        name: Login to the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      -
        name: Build and Publish Docker Image
        run: |
          mvn compile jib:build -P notification_service